In [1]:
import sys
sys.path.append("../src")

import pandas as pd
from city_mapping import canonical_city, GREIX_NATIONAL

In [2]:
with open('../data/raw/bundesbank/BBIM1.M.DE.B.A2C.A.B.A.2250.EUR.N.csv', "r", encoding = 'utf-8') as f:
    for i,line in enumerate(f):
        print(i,line.strip())
        if i > 15:
            break

0 ﻿"",BBIM1.M.DE.B.A2C.A.B.A.2250.EUR.N,BBIM1.M.DE.B.A2C.A.B.A.2250.EUR.N_FLAGS
1 "",New business (volumes) of German banks / Housing loans to households / SUD231,
2 BBK_UNIT_ENG,,
3 Comment (in english),"The MFI interest rate statistics gathered on a harmonised basis in the euro area are collected in Germany on a sample basis (stratified sample). The reported volumes of new business are grossed up to form total results for Germany. Up to May 2010 the weighting scheme followed the Horvitz-Thomson estimator (an individual expansion factor for each reporting agent). From June 2010 for each stratum an individual expansion factor is used to gross-up the reported volumes of all reporting agents of the same stratum. Then the grossed-up volumes per stratum are added to calculate the aggregated volume of new business. Secured and unsecured loans for home purchase, including building and home improvements; including loans granted by building and loan associations and interim credits as well as transmitted loans granted by the reporting agents in their own name and for their own account. Excluding overdrafts.",
4 Decimals,0,
5 Time format code,P1M,
6 category,ZREK,
7 unit multiplier,Millions,
8 last update,2026-07-31 09:51:42,
9 2003-01,15547,
10 2003-02,12498,
11 2003-03,14210,
12 2003-04,16540,
13 2003-05,12279,
14 2003-06,13149,
15 2003-07,17231,
16 2003-08,13437,

In [3]:
for fname in ["BBIM1.M.DE.B.A2C.A.R.A.2250.EUR.N.csv", "BBIM1.M.DE.B.A2C.P.R.A.2250.EUR.N.csv"]:
    print("===", fname, "===")
    with open(f"../data/raw/bundesbank/{fname}", "r", encoding = 'utf-8') as f:
        for i,line in enumerate(f):
            print(i,line.strip())
            if i > 10:
                break
    print()

=== BBIM1.M.DE.B.A2C.A.R.A.2250.EUR.N.csv ===
0 ﻿"",BBIM1.M.DE.B.A2C.A.R.A.2250.EUR.N,BBIM1.M.DE.B.A2C.A.R.A.2250.EUR.N_FLAGS
1 "",Effective interest rates of German banks / New business / Housing loans to households / SUD131Z,
2 BBK_UNIT_ENG,,
3 Comment (in english),"The MFI interest rate statistics gathered on a harmonised basis in the euro area are collected in Germany on a sample basis (stratified sample). Volume-weighted average rates of all new agreements concluded during the reporting month. (Up to May 2010 the aggregated interest rate was calculated by weighting the reported interest rates with the reported volumes of new business. From June 2010 the interest rates per stratum are calculated by weighting the reported interest rates with the reported volumes of new business. Then the interest rate for Germany is aggregated by weighting the interest rates of each stratum with the grossed-up volumes of the same stratum.) The effective interest rates may always be calculated either as annualised agreed interest rates or as narrowly defined effective rates. Both calculation methods cover all interest payments on deposits and loans but not any other related charges which may occur for enquiries, administration, preparation of the documents, guarantees and credit insurance. Disagios are regarded as interest payments and included in the interest rate calculation. The annualised agreed interest rate and the narrowly defined effective rate differ in the underlying method of annualising interest rate payments. Secured and unsecured loans for home purchase, including building and home improvements; including loans granted by building and loan associations and interim credits as well as transmitted loans granted by the reporting agents in their own name and for their own account. Excluding overdrafts.",
4 Decimals,2,
5 Time format code,P1M,
6 category,ZREK,
7 unit multiplier,One,
8 last update,2026-07-31 09:51:43,
9 2003-01,5.32,
10 2003-02,5.13,
11 2003-03,5.02,

=== BBIM1.M.DE.B.A2C.P.R.A.2250.EUR.N.csv ===
0 ﻿"",BBIM1.M.DE.B.A2C.P.R.A.2250.EUR.N,BBIM1.M.DE.B.A2C.P.R.A.2250.EUR.N_FLAGS
1 "",Effective interest rates of German banks / New business / Housing loans to households with an initial rate fixation of over 10 years / SUD119,
2 BBK_UNIT_ENG,,
3 Comment (in english),"The MFI interest rate statistics gathered on a harmonised basis in the euro area are collected in Germany on a sample basis (stratified sample). Volume-weighted average rates of all new agreements concluded during the reporting month. (Up to May 2010 the aggregated interest rate was calculated by weighting the reported interest rates with the reported volumes of new business. From June 2010 the interest rates per stratum are calculated by weighting the reported interest rates with the reported volumes of new business. Then the interest rate for Germany is aggregated by weighting the interest rates of each stratum with the grossed-up volumes of the same stratum.) The effective interest rates are calculated either as annualised agreed interest rates or as narrowly defined effective rates. Both calculation methods cover all interest payments on deposits and loans but not any other related charges which may occur for enquiries, administration, preparation of the documents, guarantees and credit insurance. Disagios are regarded as interest payments and included in the interest rate calculation. The annualised agreed interest rate and the narrowly defined effective rate differ in the underlying method of annualising interest rate payments. Secured and unsecured loans for home purchase, including building and home improvements; including loans granted by building and loan associations and interim credits as well as transmitted loans granted by the reporting agents in their own name and for their own account.",
4 Decimals,2,
5 Time format code,P1M,
6 category,ZREK,
7 unit multiplier,One,
8 last update,2026-07-31 09:51:43,
9 2003-01,5.38,
10 2003-02,5.19,
11 2003-03,5.12,

In [4]:
df4a = pd.read_csv('../data/raw/bundesbank/BBIM1.M.DE.B.A2C.A.B.A.2250.EUR.N.csv',
                  skiprows = 9,
                  header = None,
                  names = ['Date', 'Volume_millions', 'Flag'])
df4a.head()

      Date Volume_millions Flag
0  2003-01           15547  NaN
1  2003-02           12498  NaN
2  2003-03           14210  NaN
3  2003-04           16540  NaN
4  2003-05           12279  NaN

In [5]:
df4b = pd.read_csv('../data/raw/bundesbank/BBIM1.M.DE.B.A2C.A.R.A.2250.EUR.N.csv',
                  skiprows = 9,
                  header = None,
                  names = ['Date', 'Interest_rate', 'Flag'])
df4b.head()

      Date Interest_rate Flag
0  2003-01          5.32  NaN
1  2003-02          5.13  NaN
2  2003-03          5.02  NaN
3  2003-04          4.98  NaN
4  2003-05          4.90  NaN

In [6]:
df4c = pd.read_csv('../data/raw/bundesbank/BBIM1.M.DE.B.A2C.P.R.A.2250.EUR.N.csv',
                  skiprows = 9,
                  header = None,
                  names = ['Date', 'Interest_rate_10yr_fixed', 'Flag'])
df4c.head()

      Date Interest_rate_10yr_fixed Flag
0  2003-01                     5.38  NaN
1  2003-02                     5.19  NaN
2  2003-03                     5.12  NaN
3  2003-04                     5.17  NaN
4  2003-05                     5.03  NaN

In [7]:
print(df4a.shape)
print(df4a.dtypes)

(283, 3)
Date               object
Volume_millions    object
Flag               object
dtype: object

In [8]:
df4a['Volume_millions'].unique()[-20:]

array(['16989', '19743', '19077', '22151', '21500', '19870', '19234',
       '22489', '18734', '18834', '20060', '19614', '19553', '19014',
       '18710', '24167', '21192', '17219', '19781',
       'Comment on 2010-06: Change of the grossing-up procedure according to the ECB (Guideline ECB/2014/15)'],
      dtype=object)

In [9]:
non_numeric_a = df4a[~df4a['Volume_millions'].str.replace(",","").str.isnumeric()]
print(non_numeric_a)

    Date                                    Volume_millions Flag
282  NaN  Comment on 2010-06: Change of the grossing-up ...  NaN

In [10]:
df4a['Date'].isna().sum()

1

In [11]:
df4a_clean = df4a[df4a['Date'].notna()].copy()

In [12]:
df4a_clean.shape

(282, 3)

In [13]:
df4a_clean["Volume_millions"] = df4a_clean["Volume_millions"].astype(int)
print(df4a_clean.dtypes)

Date               object
Volume_millions     int64
Flag               object
dtype: object

In [14]:
print(df4a_clean.duplicated().sum())
print(df4a_clean["Volume_millions"].describe())

0
count      282.000000
mean     17542.794326
std       3662.537904
min       9950.000000
25%      14890.250000
50%      16795.000000
75%      19895.750000
max      32270.000000
Name: Volume_millions, dtype: float64

In [15]:
df4a_clean.to_csv("../data/clean/bundesbank_lending_volume.csv", index=False)

In [16]:
df4b.head()

      Date Interest_rate Flag
0  2003-01          5.32  NaN
1  2003-02          5.13  NaN
2  2003-03          5.02  NaN
3  2003-04          4.98  NaN
4  2003-05          4.90  NaN

In [17]:
print(df4b.shape)
print(df4b.dtypes)

(283, 3)
Date             object
Interest_rate    object
Flag             object
dtype: object

In [18]:
df4b['Interest_rate'].unique()[-20:]

array(['3.79', '3.93', '3.94', '4.02', '3.85', '3.83', '3.86', '3.91',
       '3.95', '3.92', '3.65', '3.59', '3.58', '3.71', '3.74', '3.70',
       '3.77', '3.72', '3.84',
       'Comment on 2010-06: Change of the grossing-up procedure according to the ECB (Guideline ECB/2014/15)'],
      dtype=object)

In [19]:
non_numeric_b = df4b[~df4b['Interest_rate'].astype(str).str.replace(",","",1).str.isnumeric()]
print(non_numeric_b)

        Date                                      Interest_rate  \
0    2003-01                                               5.32
1    2003-02                                               5.13
2    2003-03                                               5.02
3    2003-04                                               4.98
4    2003-05                                               4.90
..       ...                                                ...
278  2026-03                                               3.72
279  2026-04                                               3.84
280  2026-05                                               3.93
281  2026-06                                               3.95
282      NaN  Comment on 2010-06: Change of the grossing-up ...

                  Flag
0                  NaN
1                  NaN
2                  NaN
3                  NaN
4                  NaN
..                 ...
278                NaN
279                NaN
280                NaN
281  Provisional value
282                NaN

[283 rows x 3 columns]

In [42]:
df4b['Date'].isna().sum()

1

In [72]:
df4b_clean = df4b[df4b['Date'].notna()].copy()
print(df4b_clean.shape)

(282, 3)

In [74]:
df4b_clean["Interest_rate"] = df4b_clean["Interest_rate"].astype(float)
print(df4b_clean.dtypes)

Date              object
Interest_rate    float64
Flag              object
dtype: object

In [76]:
print(df4b_clean.duplicated().sum())
print(df4b_clean["Interest_rate"].describe())

0
count    282.000000
mean       3.247411
std        1.293677
min        1.160000
25%        1.880000
50%        3.585000
75%        4.227500
max        5.480000
Name: Interest_rate, dtype: float64

In [56]:
df4b_clean.to_csv("../data/clean/bundesbank_interest_rate_all.csv", index=False)

In [58]:
df4c.head()

      Date Interest_rate_10yr_fixed Flag
0  2003-01                     5.38  NaN
1  2003-02                     5.19  NaN
2  2003-03                     5.12  NaN
3  2003-04                     5.17  NaN
4  2003-05                     5.03  NaN

In [20]:
print(df4c.shape)
print(df4c.dtypes)

(283, 3)
Date                        object
Interest_rate_10yr_fixed    object
Flag                        object
dtype: object

In [62]:
df4c['Interest_rate_10yr_fixed'].unique()[-20:]

array(['3.89', '3.85', '3.90', '3.92', '3.65', '3.69', '3.68', '3.71',
       '3.60', '3.50', '3.45', '3.39', '3.41', '3.63', '3.73', '3.72',
       '3.91', '3.97', '3.98',
       'Comment on 2010-06: Change of the grossing-up procedure according to the ECB (Guideline ECB/2014/15)'],
      dtype=object)

In [64]:
non_numeric_c = df4c[~df4c['Interest_rate_10yr_fixed'].astype(str).str.replace(",","",1).str.isnumeric()]
print(non_numeric_c)

        Date                           Interest_rate_10yr_fixed  \
0    2003-01                                               5.38
1    2003-02                                               5.19
2    2003-03                                               5.12
3    2003-04                                               5.17
4    2003-05                                               5.03
..       ...                                                ...
278  2026-03                                               3.74
279  2026-04                                               3.91
280  2026-05                                               3.97
281  2026-06                                               3.98
282      NaN  Comment on 2010-06: Change of the grossing-up ...

                  Flag
0                  NaN
1                  NaN
2                  NaN
3                  NaN
4                  NaN
..                 ...
278                NaN
279                NaN
280                NaN
281  Provisional value
282                NaN

[283 rows x 3 columns]

In [66]:
df4c['Date'].isna().sum()

1

In [70]:
df4c_clean = df4c[df4c['Date'].notna()].copy()
print(df4c_clean.shape)

(282, 3)

In [80]:
df4c_clean["Interest_rate_10yr_fixed"] = df4c_clean["Interest_rate_10yr_fixed"].astype(float)
print(df4c_clean.dtypes)

Date                         object
Interest_rate_10yr_fixed    float64
Flag                         object
dtype: object

In [82]:
print(df4c_clean.duplicated().sum())
print(df4c_clean["Interest_rate_10yr_fixed"].describe())

0
count    282.000000
mean       3.300142
std        1.290507
min        1.110000
25%        1.970000
50%        3.595000
75%        4.465000
max        5.380000
Name: Interest_rate_10yr_fixed, dtype: float64

In [84]:
df4c_clean.to_csv("../data/clean/bundesbank_interest_rate_10yr_fixed.csv", index=False)